package main.java.com.filter.demofilter;
import java.io.IOException;

import javax.servlet.Filter;

import javax.servlet.FilterChain;

import javax.servlet.FilterConfig;

import javax.servlet.ServletException;

import javax.servlet.ServletRequest;

import javax.servlet.ServletResponse;

import javax.servlet.annotation.WebFilter;

import javax.servlet.annotation.WebInitParam;


@WebFilter(filterName = "F2", servletNames = {"S2"}, initParams = {

    @WebInitParam(name = "fmsg", value = "Hello from Filter F2")})

public class F2 implements Filter {

    

    private FilterConfig filterConfig = null;


    public F2() {

    }


    private void doBeforeProcessing(

            ServletRequest request,

            ServletResponse response)

            throws IOException,

            ServletException 

    {

          String m = filterConfig.getInitParameter("fmsg");

          response.getOutputStream().println(

                  "<p> Header generated by Filter F2</p>"+

                  "<p> Filter Config parameter fmsg is "+ m +"</p>"

          );

          request.setAttribute("fmsg",m); 

    }


    private void doAfterProcessing(

            ServletRequest request,

            ServletResponse response)

            throws IOException, ServletException {

          response.getOutputStream().println(

                  "<p> F2 read attribute 'msg' from Request "+

                  "with value </p><p>"+ request.getAttribute("msg")+"</p></p>"+

                  "<p> Footer generated by Filter F2</p>"

          );

    }


    @Override

    public void doFilter(

            ServletRequest request,

            ServletResponse response,

            FilterChain chain)

            throws IOException, ServletException {


        doBeforeProcessing(request, response);

        chain.doFilter(request, response);

        doAfterProcessing(request, response);


    }

    @Override

    public void destroy() {

   

    }

    @Override

    public void init(FilterConfig filterConfig) {

          this.filterConfig = filterConfig;

    }

}



