package main.java.com.filter.demofilter;
import java.io.IOException;

import javax.servlet.DispatcherType;

import javax.servlet.Filter;

import javax.servlet.FilterChain;

import javax.servlet.FilterConfig;

import javax.servlet.ServletException;

import javax.servlet.ServletRequest;

import javax.servlet.ServletResponse;

import javax.servlet.annotation.WebFilter;


@WebFilter(

          filterName = "F3", 

          dispatcherTypes = {DispatcherType.INCLUDE}, 

          servletNames = {"E2"}

)

public class F3 implements Filter {


    private FilterConfig filterConfig = null;


    public F3() {

    }


    private void doBeforeProcessing(

            ServletRequest request,

            ServletResponse response)

            throws IOException,

            ServletException 

    {

          response.getOutputStream().println(

                  "<p> Header generated by Filter F3</p>"

          );

    }


    private void doAfterProcessing(

            ServletRequest request,

            ServletResponse response)

            throws IOException, ServletException {

          response.getOutputStream().println(

                  "<p> Footer generated by Filter F3</p>"

          );

    }


    @Override

    public void doFilter(

            ServletRequest request,

            ServletResponse response,

            FilterChain chain)

            throws IOException, ServletException {


        doBeforeProcessing(request, response);

        chain.doFilter(request, response);

        doAfterProcessing(request, response);


    }

    @Override

    public void destroy() {

   

    }

    @Override

    public void init(FilterConfig filterConfig) {

          this.filterConfig = filterConfig;

    }

}


